### PR TITLE
add support for updating email

### PR DESCRIPTION
**Pull request by sunil567**

### CODE REVIEW

**Comment by jnix-unbound** [comment]
@sunil567 Will this change require one API call to fetch the strongmail ID and then a second to do the update?  Just chiming in because, as far as I know, the user model explicitly does not contain a reference to Strongmail's FK for the member.

**Comment by sunil567** [comment]
@jnix-unbound Yes, you are right, this change will require an API call to fetch the strongmail member. Existing `Strongmail.fetch` method will be used for that.

**Comment by jnix-unbound** [comment]
LGTM :shipit:

**Comment by sunil567** [comment]
@dskvr May you merge it, so I can update pro Gemfile.

**Pull request merged**
